[tool.bumpversion]
current_version = "0.4.4"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "ged4py/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'
