name: build_and_test

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip/wheel infrastructure
        shell: bash -l {0}
        run: |
          pip install uv
          uv pip install --system wheel

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          uv pip install --system -r requirements_dev.txt

      - name: Install pytest packages
        shell: bash -l {0}
        run: uv pip install --system pytest

      - name: List installed packages
        shell: bash -l {0}
        run: uv pip list -v

      - name: Build and install
        shell: bash -l {0}
        run: uv pip install --system -v --no-deps -e .

      - name: Run tests
        shell: bash -l {0}
        run: pytest -r a -v
