name: Run ruff check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ruff_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install ruff
        run: |
          pip install uv
          uv pip install --system ruff

      - name: Run ruff
        run: ruff check --output-format github .
